### ISSUE TITLE
Repair HackNC.com DNS

### ISSUE THREAD

**Issue by subdavis** [HackNC/fall2019#1]
Hey there, @nicholasday 

You may not be aware, but DNS for hacknc and all past websites has been broken.  Until very recently, fall2014.hacknc.com, spring2014.hacknc.com, fall2015.hacknc.com, fall2016.hacknc.com and others all pointed to past version of the website.  Many past organizers put a lot of work into those events, and every once in a while its nice to be able to go back and look at the event pages.

Github pages hosting is free and I'd like to see all of those websites available for the foreseeable future. Would you mind fixing DNS?  Thanks!

**Comment by nicholasday** [comment]
Hi @subdavis,

Thanks for bringing this to my attention! I think I have fixed all of the DNS records, but they may not have propagated yet.

**Comment by subdavis** [comment]
You did it!  Thank you.
